### ISSUE TITLE
[Bug]: Crashed when connected to bluetooth headset and playing music with 2.5X speed

### ISSUE THREAD

**Issue by sinoory** [enricocid/Music-Player-GO#480]
### What happened?

connect a Bluetooth headset，play a music .
when change the playing speed to 2.5X , the app crashed. 
attach the crash log as bellow:
10-18 11:00:34.854  2541  2541 E AndroidRuntime: FATAL EXCEPTION: main
10-18 11:00:34.854  2541  2541 E AndroidRuntime: Process: com.iven.musicplayergo.debug, PID: 2541
10-18 11:00:34.854  2541  2541 E AndroidRuntime: java.lang.IllegalArgumentException
10-18 11:00:34.854  2541  2541 E AndroidRuntime: 	at android.media.MediaPlayer.setPlaybackParams(Native Method)
10-18 11:00:34.854  2541  2541 E AndroidRuntime: 	at com.iven.musicplayergo.player.MediaPlayerHolder.setPlaybackSpeed(MediaPlayerHolder.kt:1021)
10-18 11:00:34.854  2541  2541 E AndroidRuntime: 	at 

maybe the error should be catched if IllegalArgumentException happened

### Version

4.4.20

### Device and Android version

android 12.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
try the latest version and let me know :)
https://github.com/enricocid/Music-Player-GO/actions/runs/3268232710

**Comment by enricocid** [comment]
https://drive.google.com/file/d/1FgDckBtI9NRL9giCWi2Qseltl6Z9bN2f/view?usp=drivesdk

**Comment by sinoory** [comment]
still crash

**Comment by sinoory** [comment]
this works ~
    fun safeSetPlaybackSpeed(mediaPlayer: MediaPlayer, speed: Float) {
//        with(mediaPlayer) {
//            playbackParams = playbackParams.setSpeed(try {
//                speed
//            } catch (e: IllegalArgumentException) {
//                e.printStackTrace()
//                1.0F
//            })
//        }
        with (mediaPlayer) {
            try {
                playbackParams = playbackParams.setSpeed(speed)
            } catch (e: IllegalArgumentException) {
                e.printStackTrace()
                playbackParams = playbackParams.setSpeed(1.0F)
            }
        }
    }

**Comment by enricocid** [comment]
Done. Thanks :)

**Comment by sinoory** [comment]
You're welcome：）

**Comment by sinoory** [comment]
hello，still crash， need change IllegalStateException to IllegalArgumentException in safeSetPlaybackSpeed function

**Comment by enricocid** [comment]
Fixed, thanks :)
